<div class="container">
	<div class="panel panel-primary">
<table class="table table-bordered">
	  <div class="panel-heading">
	 <?php

   foreach ($this->allwishproduct as $key => $value) {
        echo "<tr>".
     "<td >" ."Name:" .$value['name']. "</td>" 
 		
		?>
			<td><img src ="<?php echo $this->baseUrl()."/images/".$value['image'];?>" height="100" width="100"> <?php echo"</td>" .
	 		"</tr>";
 		// echo "<tr>".
 		// "<td >" . "Quantity:" . $value['quantity']. "</td>" .

 		
 }

 ?>
</div>
</div>
</table>
</div>

