<?php
    require_once "./main/header.php";
    require_once "./main/header-bot.php";
    require_once "./main/banner-top.php";
    // require_once "./main/banner.php";
    // /////////////////////////////////////
    // require_once "./main/content-bottom.php";
    // require_once "./main/product-nav.php";
    // require_once "./main/content.php";
    /////////////////////////////////////
    echo $this->layout()->content;
    /////////////////////////////////////
    //require_once "./main/coupons.php";
    //require_once "./main/footer.php";
    require_once "./main/login.php";
?>
  </body>
</html>
