<?php
    require_once "./admin/header.php";
    require_once "./admin/dashboard.php";
    /* Initialize action controller here */
    /* Initialize action controller here */
    $authorization = Zend_Auth::getInstance();
    $storage=$authorization->getStorage();
    $userdata=$storage->read();

    if (!$authorization->hasIdentity() || $userdata->type == 3)
    {
        $this->redirect('/');
    }

?>

<?php    
    echo $this->layout()->content;
    require_once "./admin/footer.php";

?>
