
<div class="container">
  <div class="panel panel-primary">
    <div class="panel-heading">

<?php
$upload='/images';
// var_dump($this->product);
// exit;
?>
        <center><img src ="<?php echo $this->baseUrl()."/images/".$this->product['image'];?>" height="300" width="300"></center>
    </div>
    <div class="panel-body">

      <h4>Name: <?php echo $this->product['name']; ?></h4>
      <h4>Price: <?php echo $this->product['price']; ?></h4>
      <h4>Rate: <?php echo $this->product['rate']; ?></h4>
      <h4>Description: <?php echo $this->product['pdesc']; ?></h4>
  </div>
</div>



