<div class="container">
	<div class="panel panel-primary">
<table class="table table-bordered">
	  <div class="panel-heading">
	 <?php
$upload='/images';
//var_dump($this->product);
//die;

	foreach ($this->product as $key => $value) {
		# code...
echo "<tr>";
echo "<td>"; ?>

<img src ="<?php echo $this->baseUrl()."/images/".$value['image'];?>" height="100" width="100"> <?php
 echo "<td>";
	echo "</tr>";
		echo "<tr>".
		"<td >" ."Name:" .$value['name']. "</td>" .
		"</tr>";
		echo "<tr>".
		"<td >" . "Price:" .$value['price']. "</td>" .
		"</tr>";
		echo "<tr>".
		"<td >" . "Rate:" . $value['rate']. "</td>" .
		"<td> <a class='btn btn-default btn-lg active' href='detailsforcustomer/pid/".$value['id']."'> Details </a></td>".
		"</tr>";
}
?>
