<h1 class="text-center">Total Statistics Page</h1>
	<div class="panel panel-primary">
          <!-- /.box-header -->
          <div class="box-body">
              <ul class="products-list product-list-in-box">
                  <?php $total = 0 ?>
                  <?php foreach ($this->statisticproduct as $key => $value): ?>
                      <?php $total += $value['quantity']*$value['price']?>
                      <li class="item">
                          <div class="product-img">
                              <img src="<?php $this->baseUrl() ?>/images/<?=$value['image']?>" alt="<?=$value['name']?>">
                          </div>
                          <div class="product-info">
                              <a href="<?php $this->baseUrl() ?>/product/details/pid/<?=$value['id']?>" class="product-title"><?=$value['name']?>

                                  <?php if($value['price']<50): ?>
                                      <span class="label label-danger pull-right">$<?=$value['quantity']*$value['price']?></span>
                                  <?php elseif($value['price']<100): ?>
                                      <span class="label label-warning pull-right">$<?=$value['quantity']*$value['price']?></span>
                                  <?php elseif($value['price']<500): ?>
                                      <span class="label label-info pull-right">$<?=$value['quantity']*$value['price']?></span>
                                  <?php else: ?>
                                      <span class="label label-success pull-right">$<?=$value['quantity']*$value['price']?></span>
                                  <?php endif; ?>

                              </a>
                              <span class="product-description">
                                <?=$value['pdesc']?>
                        </span>
                          </div>
                      </li>

                  <?php endforeach; ?>

              </ul>
          </div>
          <!-- /.box-body -->
    </div>
