<div class="container">
	<div class="panel panel-primary">
<table class="table table-bordered">
	  <div class="panel-heading">
	 <?php

   foreach ($this->statisticproduct as $key => $value) {
     echo "<tr>".

     "<td >" ."Name:" .$value['name']. "</td>" .
 		"<tr>";
		 echo "<tr>".
 		"<td >" . "MONEY Gained:" .$value['price']. "</td>" .
 		 "</tr>";
 		 echo "<tr>".
 		"<td >" . "Quantity:" . $value['quantity']. "</td>" .

 		"</tr>";
 }
 ?>
