<?php
/*
 *
 * used in Admin Dashboard
 *
*/
    require_once("./admin/dashboard.php");
?>
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3><center>Details</center></h3>
        </div>
        <div class="panel-body">
            <table class="table table-bordered">
                <?php
                    echo "<h3>Category Name:</h3>";
                    echo  $this->category['name'];
                    echo "<h3>Description:</h3>";
                    echo $this->category['cdesc'];
                ?>
            </table>
        </div>
        <div class="panel-body">
            <img src="<?php echo ($this->baseUrl()."/images/".$this->category['image']);?>" width="300px">
        </div>
    </div>
</div>
