<?php
require_once("./admin/dashboard.php");
?>
<div class="container">
    <h1 class="text-center">Users Page</h1>


    <br>

    <table id="datatable" class="table table-striped table-bordered table-hover table-condensed" width=100%>
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Category Name
                </th>
                <th>
                    Parent
                </th>
                <th colspan="3">
                    <center>
                        Action
                    </center>
                </th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->category as $key => $value) : ?>
            <tr>
                <td>
                    <?=$value['id']?>
                </td>
                <td>
                    <?=$value['name']?>
                </td>
                <td>
                    <?=$value['cdesc']?>
                </td>
                <td>
                    <a class='btn btn-info text-center' href='<?=$this->baseUrl();?>/category/details/cat_id/<?=$value['id'];?>'>Details</a>
                </td>
                <td>
                    <a class='btn btn-warning text-center' href='<?=$this->baseUrl();?>/category/update/cat_id/<?=$value['id'];?>'>Update</a>
                </td>
                <td>
                    <a class='btn btn-danger text-center' href='<?=$this->baseUrl();?>/category/delete/cat_id/<?=$value['id'];?>'>Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>



        </tbody>
    </table>
</div>
<div class="btn-group">
    <button type="button" class="btn btn-default">
        <a class="btn btn-primary" href='/category/add/'>Add New Category</a>
    </button>
</div>