<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Category</th>
        <th>Parent</th>
        <th colspan="4"><center>Action</center></th>
    </tr>
<?php
foreach($this->category as $key => $value)
{
    echo "<tr>".
        "<td>" . $value['cat_id'] . "</td>" .
        "<td>" . $value['cname'] . "</td>" .
        "<td>" . $value['cdesc'] . "</td>" .
        "<td> <a href='add/cat_id/".$value['cat_id']."'> ADD </a></td>" .
        "<td> <a href='details/cat_id/".$value['cat_id']."'> Details </a> </td>" .
        "<td> <a href='delete/cat_id/".$value['cat_id']."'> Delete </a></td>" .
        "<td> <a href='update/cat_id/".$value['cat_id']."'> Update </a></td>" ."</tr>";
}
?>
</table>